common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: dv
  password:
  min_messages: WARNING
  host: localhost

development:
  <<: *common
  database: clique_development

test:
  <<: *common
  database: clique_test
